version: '3.4'

services:
  webmvc:
    image: ${DOCKER_REGISTRY-}sprihards/weather_app_mvc:v1.21.1.22.3
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
  batchqueue:
    image: ${DOCKER_REGISTRY-}sprihards/weather_app_batchqueue:v1.21.1.22.3
    environment:
      WeatherApiConsumerConfiguration__ApiId: "8cc7bc078bc177ddd9d1deb683e9045e"
    depends_on:
      - db
      - webmvc
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Ex0Mplew@!3kew
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql/data
volumes:
  data: