version: '3.4'

services:
  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: WebMvc/Dockerfile
    depends_on:
      - db
  batchqueue:
    image: ${DOCKER_REGISTRY-}batchqueue
    build:
      context: .
      dockerfile: BatchQueue/Dockerfile
    depends_on:
      - db
      - webmvc
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Ex0Mplew@!3kew
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql/data
volumes:
  data: